
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class DemoCategory : Singleton<DemoCategory>, IResolveRef
    {
        private readonly Dictionary<int, Demo> _dataMap;
        private readonly List<Demo> _dataList;

        public DemoCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, Demo>();
            _dataList = new List<Demo>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                Demo _v;
                _v = Demo.DeserializeDemo(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, Demo> DataMap => _dataMap;
        public List<Demo> DataList => _dataList;

        public Demo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public Demo Get(int key) => _dataMap[key];
        public Demo this[int key] => _dataMap[key];
        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
