
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class Demo : BeanBase
    {
        public Demo(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Key = _buf.ReadString();

            PostInit();
        }

        public static Demo DeserializeDemo(ByteBuf _buf)
        {
            return new Demo(_buf);
        }

        public readonly int Id;

        /// <summary>
        /// 策划备注不导表
        /// </summary>
        public readonly string Key;


        public const int __ID__ = 2126339;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            PostResolve();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Key:" + Key + ","
            + "}";
        }

        partial void PostInit();
        partial void PostResolve();
    }
}
