
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class StartZoneConfigCategory : Singleton<StartZoneConfigCategory>, IResolveRef
    {
        private readonly List<StartZoneConfig> _dataList;

        private Dictionary<(string, int), StartZoneConfig> _dataMapUnion;

        public StartZoneConfigCategory(ByteBuf _buf)
        {
            _dataList = new List<StartZoneConfig>();

            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                StartZoneConfig _v;
                _v = StartZoneConfig.DeserializeStartZoneConfig(_buf);
                _dataList.Add(_v);
            }
            _dataMapUnion = new Dictionary<(string, int), StartZoneConfig>();
            foreach(var _v in _dataList)
            {
                _dataMapUnion.Add((_v.StartConfig, _v.Id), _v);
            }
        }

        public List<StartZoneConfig> DataList => _dataList;

        public StartZoneConfig Get(string StartConfig, int Id) => _dataMapUnion.TryGetValue((StartConfig, Id), out StartZoneConfig __v) ? __v : null;

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
