
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class StartMachineConfigCategory : Singleton<StartMachineConfigCategory>, IResolveRef
    {
        private readonly List<StartMachineConfig> _dataList;

        private Dictionary<(string, int), StartMachineConfig> _dataMapUnion;

        public StartMachineConfigCategory(ByteBuf _buf)
        {
            _dataList = new List<StartMachineConfig>();

            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                StartMachineConfig _v;
                _v = StartMachineConfig.DeserializeStartMachineConfig(_buf);
                _dataList.Add(_v);
            }
            _dataMapUnion = new Dictionary<(string, int), StartMachineConfig>();
            foreach(var _v in _dataList)
            {
                _dataMapUnion.Add((_v.StartConfig, _v.Id), _v);
            }
        }

        public List<StartMachineConfig> DataList => _dataList;

        public StartMachineConfig Get(string StartConfig, int Id) => _dataMapUnion.TryGetValue((StartConfig, Id), out StartMachineConfig __v) ? __v : null;

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
