
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class StartProcessConfigCategory : Singleton<StartProcessConfigCategory>, IResolveRef
    {
        private readonly List<StartProcessConfig> _dataList;

        private Dictionary<(string, int), StartProcessConfig> _dataMapUnion;

        public StartProcessConfigCategory(ByteBuf _buf)
        {
            _dataList = new List<StartProcessConfig>();

            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                StartProcessConfig _v;
                _v = StartProcessConfig.DeserializeStartProcessConfig(_buf);
                _dataList.Add(_v);
            }
            _dataMapUnion = new Dictionary<(string, int), StartProcessConfig>();
            foreach(var _v in _dataList)
            {
                _dataMapUnion.Add((_v.StartConfig, _v.Id), _v);
            }
        }

        public List<StartProcessConfig> DataList => _dataList;

        public StartProcessConfig Get(string StartConfig, int Id) => _dataMapUnion.TryGetValue((StartConfig, Id), out StartProcessConfig __v) ? __v : null;

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
