
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class StartSceneConfigCategory : Singleton<StartSceneConfigCategory>, IResolveRef
    {
        private readonly List<StartSceneConfig> _dataList;

        private Dictionary<(string, int), StartSceneConfig> _dataMapUnion;

        public StartSceneConfigCategory(ByteBuf _buf)
        {
            _dataList = new List<StartSceneConfig>();

            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                StartSceneConfig _v;
                _v = StartSceneConfig.DeserializeStartSceneConfig(_buf);
                _dataList.Add(_v);
            }
            _dataMapUnion = new Dictionary<(string, int), StartSceneConfig>();
            foreach(var _v in _dataList)
            {
                _dataMapUnion.Add((_v.StartConfig, _v.Id), _v);
            }
        }

        public List<StartSceneConfig> DataList => _dataList;

        public StartSceneConfig Get(string StartConfig, int Id) => _dataMapUnion.TryGetValue((StartConfig, Id), out StartSceneConfig __v) ? __v : null;

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
